local function spec(t)
  local p = require'sopa.pal'
  t = vim.tbl_deep_extend('force', {at = 'NONE', bg = -1, fg = -1, sp = -1}, t)
  return {gui = t.at, guibg = p[t.bg], guifg = p[t.fg], guisp = p[t.sp]}
end

return {
  background = spec{bg = 2, fg = 6},
  buffer_selected = spec{at = 'bold,italic', bg = 0, fg = 7},
  buffer_visible = spec{at = 'bold,italic', bg = 0, fg = 6},
  close_button = spec{at = 'bold', bg = 2, fg = 8},
  close_button_selected = spec{at = 'bold', bg = 0, fg = 8},
  close_button_visible = spec{at = 'bold', bg = 0, fg = 8},
  diagnostic = spec{at = 'bold,italic', bg = 2, fg = 9},
  diagnostic_selected = spec{at = 'bold,italic', bg = 0, fg = 9},
  diagnostic_visible = spec{at = 'bold,italic', bg = 0, fg = 9},
  duplicate = spec{at = 'italic', bg = 2, fg = 6},
  duplicate_selected = spec{at = 'italic', bg = 0, fg = 7},
  duplicate_visible = spec{at = 'italic', bg = 0, fg = 6},
  error = spec{at = 'bold,italic', bg = 2, fg = 8},
  error_diagnostic = spec{at = 'bold,italic', bg = 2, fg = 8},
  error_diagnostic_selected = spec{at = 'bold,italic', bg = 0, fg = 8},
  error_diagnostic_visible = spec{at = 'bold,italic', bg = 0, fg = 8},
  error_selected = spec{at = 'bold,italic', bg = 0, fg = 8},
  error_visible = spec{at = 'bold,italic', bg = 0, fg = 8},
  fill = spec{bg = 1},
  indicator_selected = spec{at = 'bold', bg = 0, fg = 7},
  info = spec{at = 'bold,italic', bg = 2, fg = 11},
  info_diagnostic = spec{at = 'bold,italic', bg = 2, fg = 11},
  info_diagnostic_selected = spec{at = 'bold,italic', bg = 0, fg = 11},
  info_diagnostic_visible = spec{at = 'bold,italic', bg = 0, fg = 11},
  info_selected = spec{at = 'bold,italic', bg = 0, fg = 11},
  info_visible = spec{at = 'bold,italic', bg = 0, fg = 11},
  modified = spec{bg = 2, fg = 11},
  modified_selected = spec{bg = 0, fg = 11},
  modified_visible = spec{bg = 0, fg = 11},
  pick = spec{at = 'bold,italic', bg = 2, fg = 12},
  pick_selected = spec{at = 'bold,italic', bg = 0, fg = 12},
  pick_visible = spec{at = 'bold,italic', bg = 0, fg = 12},
  separator = spec{bg = 1, fg = 1},
  separator_selected = spec{bg = 1, fg = 1},
  separator_visible = spec{bg = 1, fg = 1},
  tab = spec{bg = 2, fg = 6},
  tab_close = spec{at = 'bold', bg = 1, fg = 8},
  tab_selected = spec{at = 'bold', bg = 0, fg = 7},
  warning = spec{at = 'bold,italic', bg = 2, fg = 10},
  warning_diagnostic = spec{at = 'bold,italic', bg = 2, fg = 10},
  warning_diagnostic_selected = spec{at = 'bold,italic', bg = 0, fg = 10},
  warning_diagnostic_visible = spec{at = 'bold,italic', bg = 0, fg = 10},
  warning_selected = spec{at = 'bold,italic', bg = 0, fg = 10},
  warning_visible = spec{at = 'bold,italic', bg = 0, fg = 10},
}
