return {
  Character = {fg = 11},
  ColorColumn = {bg = 1},
  Comment = {fg = 6},
  Conceal = {at = 'italic', fg = 12},
  Constant = {fg = 9},
  CursorColumn = {bg = 2},
  CursorLine = 'CursorColumn',
  CursorLineNr = {at = 'bold', fg = 6},
  DiagnosticError = {fg = 8},
  DiagnosticHint = {fg = 9},
  DiagnosticInfo = {fg = 11},
  DiagnosticWarn = {fg = 10},
  DiffAdd = {at = 'bold', bg = 11, fg = 0},
  diffAdded = {fg = 11},
  DiffChange = {at = 'bold', bg = 9, fg = 0},
  DiffDelete = {at = 'bold', bg = 8, fg = 0},
  diffFile = 'Comment',
  diffLine = {fg = 15},
  diffRemoved = {fg = 8},
  diffSubname = {fg = 14},
  DiffText = {at = 'bold', bg = 10, fg = 0},
  Directory = {at = 'bold', fg = 15},
  Error = {at = 'bold', bg = 8, fg = 0},
  ErrorMsg = {at = 'bold', fg = 8},
  FoldColumn = 'LineNr',
  Folded = {bg = 2, fg = 6},
  htmlEndTag = 'htmlTag',
  htmlTag = 'Comment',
  Identifier = {fg = 13},
  Ignore = {},
  IncSearch = {at = 'bold,reverse', fg = 14},
  LineNr = {fg = 5},
  MatchParen = {at = 'bold', bg = 4, fg = 15},
  NonText = {at = 'bold', fg = 4},
  MoreMsg = {at = 'bold', fg = 11},
  Normal = {bg = 0, fg = 7},
  Number = {fg = 10},
  Pmenu = {bg = 1, fg = 6},
  PmenuSBar = {bg = 2},
  PmenuSel = {bg = 2, fg = 7},
  PmenuThumb = {bg = 3},
  Preproc = {fg = 8},
  Question = {at = 'bold', fg = 9},
  Search = {at = 'bold', bg = 10, fg = 0},
  SignColumn = 'LineNr',
  Special = {fg = 12},
  SpecialKey = {at = 'italic', fg = 12},
  SpellBad = {at = 'undercurl', sp = 8},
  SpellCap = {at = 'undercurl', sp = 11},
  SpellLocal = {at = 'undercurl', sp = 10},
  SpellRare = {at = 'undercurl', sp = 9},
  Statement = {fg= 15},
  StatusLine = {at = 'bold', bg = 2, fg = 7},
  StatusLineNC = {bg = 1, fg = 5},
  String = 'Character',
  TabLine = {bg = 2, fg = 6},
  TabLineFill = {bg = 1},
  TabLineSel = {at = 'bold', bg = 0, fg = 7},
  Title = {at = 'bold', fg = 12},
  Todo = {at = 'bold', fg = 12},
  Type = {fg = 14},
  Underlined = {at = 'underline'},
  VertSplit = {bg = 1, fg = 4},
  vimCommentTitle = 'Todo',
  Visual = {bg = 3},
  WarningMsg = {at = 'bold', fg = 10},
  Whitespace = {fg = 5},
  WildMenu = {at = 'bold', bg = 0, fg = 6},
}
